### ISSUE TITLE
欢迎参与 fduthesis 的开发

### ISSUE THREAD

**Issue by stone-zeng** [Wonsa0823/FDUBachelor-template-for-LaTeX#1]
同学你好！我在之前一段时间编写了一个模板 [fduthesis](https://github.com/Stone-Zeng/fduthesis)，并且已经发布到了 [CTAN](https://www.ctan.org/pkg/fduthesis)。如果有兴趣的话，欢迎你尝试一下（~~言下之意你可以不用自己造轮子的~~）。可能的话，也希望能向同学推广一下。

我那个模板实际上用的人不多，另外由于不知道其他院系对格式的具体要求，所以只针对我们物理系的要求做了适配。但我在考虑构建一个比较统一的框架（现在封面可以比较自由地修改），应该可以满足各种要求。

之前也有不少学长做过编写模板的尝试，但流传并不广，同学之间流通的基本都是过时的东西。所以非常希望能有一个比较统一的模板并且有人长期维护，大概像清华的 thuthesis 或者交大、科大他们一样。

**Comment by Wonsa0823** [comment]
我这个只是改别人的，自己不会造轮子。。。
